version: '3.2'
services:
  web:
    image: hk5demandsweb:fdf19ad
    command: node ./bin/www
    restart: unless-stopped
    environment:
      - HTTP_PORT=9091
      - SERVERURL=http://host.docker.internal:8080
    ports:
      - '9091:9091'
    volumes:
      - /opt/hk5demandsweb/data:/usr/app/hk5demandsweb/data
      